#!/usr/bin/env bash

docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v $(pwd):/var/www/html \
    -w /var/www/html \
    laravelsail/php81-composer:latest \
    composer install --ignore-platform-reqs;

cp .env.example .env;

vendor/bin/sail up -d; 

sleep 5s;

vendor/bin/sail artisan key:generate; 

sleep 5s;

vendor/bin/sail artisan migrate; 

vendor/bin/sail artisan horizon;
